# Generated by Django 2.2.3 on 2019-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
