# Generated by Django 2.2.3 on 2019-07-11 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20190706_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
    ]
