# Generated by Django 2.2.3 on 2019-07-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190711_0324'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenCompra',
            new_name='Factura',
        ),
    ]
