# Generated by Django 2.2.3 on 2019-08-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20190723_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
